In [10]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import math

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import mean_squared_error

In [11]:
dataset = pd.read_csv("eda_data.csv")
dataset.head()

,Unnamed: 0,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,...,age,python_yn,R_yn,spark,aws,excel,job_simp,seniority,desc_len,num_comp
0,0,Data Scientist,$53K-$91K (Glassdoor est.),"Data Scientist\nLocation: Albuquerque, NM\nEdu...",3.8,Tecolote Research\n3.8,"Albuquerque, NM","Goleta, CA",501 to 1000 employees,1973,...,47,1,0,0,0,1,data scientist,na,2536,0
1,1,Healthcare Data Scientist,$63K-$112K (Glassdoor est.),What You Will Do:\n\nI. General Summary\n\nThe...,3.4,University of Maryland Medical System\n3.4,"Linthicum, MD","Baltimore, MD",10000+ employees,1984,...,36,1,0,0,0,0,data scientist,na,4783,0
2,2,Data Scientist,$80K-$90K (Glassdoor est.),"KnowBe4, Inc. is a high growth information sec...",4.8,KnowBe4\n4.8,"Clearwater, FL","Clearwater, FL",501 to 1000 employees,2010,...,10,1,0,1,0,1,data scientist,na,3461,0
3,3,Data Scientist,$56K-$97K (Glassdoor est.),*Organization and Job ID**\nJob ID: 310709\n\n...,3.8,PNNL\n3.8,"Richland, WA","Richland, WA",1001 to 5000 employees,1965,...,55,1,0,0,0,0,data scientist,na,3883,3
4,4,Data Scientist,$86K-$143K (Glassdoor est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,...,22,1,0,0,0,1,data scientist,na,2728,3

In [12]:
dataset = dataset.drop(columns=[
    'Unnamed: 0','Job Description',
    'Job Title','Company Name', 'company_txt', 'Location','seniority',
    'Salary Estimate', 'Headquarters', 'Size', 'Founded',
    'Type of ownership', 'Industry', 'Sector', 'Revenue', 'Competitors'
])

In [13]:
dataset.head()

,Rating,hourly,employer_provided,min_salary,max_salary,avg_salary,job_state,same_state,age,python_yn,R_yn,spark,aws,excel,job_simp,desc_len,num_comp
0,3.8,0,0,53,91,72.0,NM,0,47,1,0,0,0,1,data scientist,2536,0
1,3.4,0,0,63,112,87.5,MD,0,36,1,0,0,0,0,data scientist,4783,0
2,4.8,0,0,80,90,85.0,FL,1,10,1,0,1,0,1,data scientist,3461,0
3,3.8,0,0,56,97,76.5,WA,1,55,1,0,0,0,0,data scientist,3883,3
4,2.9,0,0,86,143,114.5,NY,1,22,1,0,0,0,1,data scientist,2728,3

In [14]:
dataset.columns

Index(['Rating', 'hourly', 'employer_provided', 'min_salary', 'max_salary',
       'avg_salary', 'job_state', 'same_state', 'age', 'python_yn', 'R_yn',
       'spark', 'aws', 'excel', 'job_simp', 'desc_len', 'num_comp'],
      dtype='object')

In [15]:
dataset = pd.get_dummies(
    dataset,
    columns=['job_state', 'job_simp'],
    drop_first=True
)

In [16]:
dataset.head()

,Rating,hourly,employer_provided,min_salary,max_salary,avg_salary,same_state,age,python_yn,R_yn,...,job_state_UT,job_state_VA,job_state_WA,job_state_WI,job_simp_data engineer,job_simp_data scientist,job_simp_director,job_simp_manager,job_simp_mle,job_simp_na
0,3.8,0,0,53,91,72.0,0,47,1,0,...,False,False,False,False,False,True,False,False,False,False
1,3.4,0,0,63,112,87.5,0,36,1,0,...,False,False,False,False,False,True,False,False,False,False
2,4.8,0,0,80,90,85.0,1,10,1,0,...,False,False,False,False,False,True,False,False,False,False
3,3.8,0,0,56,97,76.5,1,55,1,0,...,False,False,True,False,False,True,False,False,False,False
4,2.9,0,0,86,143,114.5,1,22,1,0,...,False,False,False,False,False,True,False,False,False,False

In [ ]:
X = dataset.drop(columns=['avg_salary'])
y = dataset['avg_salary']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [ ]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
model = LinearRegression()
model.fit(X_train, y_train)

In [ ]:
y_pred = model.predict(X_test)